version: "3.9"

services:
  backend:
    build: ./backend
    container_name: ia-backend
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: ia-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app          # monta tu código local
      - /app/node_modules        # evita que se pisen los node_modules del contenedor


  redis:
    image: redis:latest
    container_name: ia-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    # Para persistir datos en disco podrías añadir:
    # volumes:
    #   - ./redis-data:/data
